# Generated by Django 3.2.9 on 2022-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'O`qituvchi', 'verbose_name_plural': 'O`qituvchilar'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='question_n',
            field=models.SmallIntegerField(default=0),
        ),
    ]
