# Generated by Django 3.2.9 on 2022-03-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220312_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='text',
            new_name='javob',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='savol',
        ),
    ]
